# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-21 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='question',
        ),
        migrations.AddField(
            model_name='downvote',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feed_models.Answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upvote',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feed_models.Answer'),
            preserve_default=False,
        ),
    ]
