# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-22 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_models', '0002_auto_20190921_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('answer', 'answer'), ('upvote', 'upvote'), ('downvote', 'downvote')], max_length=256),
        ),
    ]
